import {describe, it} from "node:test";
import assert from "node:assert";

import buildTreeRecursive from "./";
import generateTree from "./";

describe('buildTreeRecursive', () => {
    it('should generate a json tree from flat array', () => {
        const data = [
            {
                aliment: 'Fruits',
                sousAliment: 'Pomme',
                sousAliment2: 'Golden',
                quantite: '100g',
                prix: '1,50€'
            },
            {
                aliment: 'Fruits',
                sousAliment: 'Pomme',
                sousAliment2: 'Pink Lady',
                quantite: '100g',
                prix: '1,00€'
            },
            {
                aliment: 'Fruits',
                sousAliment: 'Pomme',
                sousAliment2: 'Granny Smith',
                quantite: '100g',
                prix: '1,70€'
            },
            {
                aliment: 'Fruits',
                sousAliment: 'Poire',
                sousAliment2: 'William',
                quantite: '100g',
                prix: '2,10€'
            },
            {
                aliment: 'Viandes',
                sousAliment: 'Boeuf',
                sousAliment2: 'Steak',
                quantite: '100g',
                prix: '3,55€'
            },
            {
                aliment: 'Viandes',
                sousAliment: 'Veau',
                sousAliment2: 'Escalope',
                quantite: '100g',
                prix: '4.50€'
            },
            {
                aliment: 'Viandes',
                sousAliment: 'Veau',
                sousAliment2: 'Paupiette',
                quantite: '100g',
                prix: '6.50€'
            }
        ]
        const keysDepth = ['aliment', 'sousAliment', 'sousAliment2']
        const jsonTree = generateTree(data, keysDepth)
        const expectedResult = {
            'Fruits': {
                'Pomme': {
                    'Golden': {
                        aliment: 'Fruits',
                        sousAliment: 'Pomme',
                        sousAliment2: 'Golden',
                        quantite: '100g',
                        prix: '1,50€'
                    },
                    'Pink Lady': {
                        aliment: 'Fruits',
                        sousAliment: 'Pomme',
                        sousAliment2: 'Pink Lady',
                        quantite: '100g',
                        prix: '1,00€'
                    },
                    'Granny Smith': {
                        aliment: 'Fruits',
                        sousAliment: 'Pomme',
                        sousAliment2: 'Granny Smith',
                        quantite: '100g',
                        prix: '1,70€'
                    }
                },
                'Poire': {
                    'William': {
                        aliment: 'Fruits',
                        sousAliment: 'Poire',
                        sousAliment2: 'William',
                        quantite: '100g',
                        prix: '2,10€'
                    }
                }
            },
            'Viandes': {
                'Boeuf': {
                    'Steak': {
                        aliment: 'Viandes',
                        sousAliment: 'Boeuf',
                        sousAliment2: 'Steak',
                        quantite: '100g',
                        prix: '3,55€'
                    }
                },
                'Veau': {
                    'Escalope': {
                        aliment: 'Viandes',
                        sousAliment: 'Veau',
                        sousAliment2: 'Escalope',
                        quantite: '100g',
                        prix: '4.50€'
                    },
                    'Paupiette': {
                        aliment: 'Viandes',
                        sousAliment: 'Veau',
                        sousAliment2: 'Paupiette',
                        quantite: '100g',
                        prix: '6.50€'
                    }
                }
            }
        }
        assert.deepStrictEqual(jsonTree, expectedResult)
    })

    it('should generate a json tree from flat array', () => {
        const data = [
            {
                ProductId: '910254',
                ProductName: 'Ovixan 1 mg/g\nkräm/krem/emulsiovoide',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '29-03-2012',
                'N°AMM': '45580',
                'Major Country': 'SE',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290019',
                'Product National Id *': '7350064290019',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '138',
                'Product width': '30',
                'Product heigth': '38',
                'Product weight': '45,5',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910975',
                ProductName: 'Ovixan 1 mg/g\nkräm/krem/emulsiovoide',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '29-03-2012',
                'N°AMM': '45580',
                'Major Country': 'SE',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290019',
                'Product National Id *': '7350064290019',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '138',
                'Product width': '30',
                'Product heigth': '38',
                'Product weight': '45,5',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910256',
                ProductName: 'Ovixan 1 mg/g kräm/krem/emulsiovoide',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '29-03-2012',
                'N°AMM': '45580',
                'Major Country': 'SE',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290026',
                'Product National Id *': '7350064290026',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '195',
                'Product width': '38',
                'Product heigth': '44',
                'Product weight': '126,5',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910976',
                ProductName: 'Ovixan 1 mg/g kräm/krem/emulsiovoide',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '29-03-2012',
                'N°AMM': '45580',
                'Major Country': 'SE',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290026',
                'Product National Id *': '7350064290026',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '195',
                'Product width': '38',
                'Product heigth': '44',
                'Product weight': '126,5',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910254',
                ProductName: 'Ovixan 1 mg/g\nkräm/krem/emulsiovoide',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '29-12-2011',
                'N°AMM': 'IS/1/11/136/01',
                'Major Country': 'IS',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290019',
                'Product National Id *': '7350064290019',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '138',
                'Product width': '30',
                'Product heigth': '38',
                'Product weight': '45,5',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910975',
                ProductName: 'Ovixan 1 mg/g\nkräm/krem/emulsiovoide',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '29-12-2011',
                'N°AMM': 'IS/1/11/136/01',
                'Major Country': 'IS',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290019',
                'Product National Id *': '7350064290019',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '138',
                'Product width': '30',
                'Product heigth': '38',
                'Product weight': '45,5',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910256',
                ProductName: 'Ovixan 1 mg/g kräm/krem/emulsiovoide1',
                'Generic Name': 'Mometasone furoate1',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '29-12-2011',
                'N°AMM': 'IS/1/11/136/01',
                'Major Country': 'IS',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290026',
                'Product National Id *': '7350064290026',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '195',
                'Product width': '38',
                'Product heigth': '44',
                'Product weight': '126,5',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910976',
                ProductName: 'Ovixan 1 mg/g kräm/krem/emulsiovoide1',
                'Generic Name': 'Mometasone furoate1',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '29-12-2011',
                'N°AMM': 'IS/1/11/136/01',
                'Major Country': 'IS',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream1',
                'Code article 57': '',
                'GTIN*': '7350064290026',
                'Product National Id *': '7350064290026',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '195',
                'Product width': '38',
                'Product heigth': '44',
                'Product weight': '126,5',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910255',
                ProductName: 'Ovixan 1 mg/g kräm/krem/emulsiovoide1',
                'Generic Name': 'Mometasone furoate1',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '11-01-2012',
                'N°AMM': '29453',
                'Major Country': 'FI',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream2',
                'Code article 57': '',
                'GTIN*': '7350064290224',
                'Product National Id *': '7350064290224',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '138',
                'Product width': '30',
                'Product heigth': '38',
                'Product weight': '45,5',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910977',
                ProductName: 'Ovixan 1 mg/g kräm/krem/emulsiovoide',
                'Generic Name': 'Mometasone furoate1',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '11-01-2012',
                'N°AMM': '29453',
                'Major Country': 'FI',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290224',
                'Product National Id *': '7350064290224',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '138',
                'Product width': '30',
                'Product heigth': '38',
                'Product weight': '45,5',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910257',
                ProductName: 'Ovixan 1 mg/g kräm/krem/emulsiovoide',
                'Generic Name': 'Mometasone furoate1',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '11-01-2012',
                'N°AMM': '29453',
                'Major Country': 'FI',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290231',
                'Product National Id *': '7350064290231',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '195',
                'Product width': '38',
                'Product heigth': '44',
                'Product weight': '126,5',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910978',
                ProductName: 'Ovixan 1 mg/g kräm/krem/emulsiovoide',
                'Generic Name': 'Mometasone furoate1',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '11-01-2012',
                'N°AMM': '29453',
                'Major Country': 'FI',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290231',
                'Product National Id *': '7350064290231',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '195',
                'Product width': '38',
                'Product heigth': '44',
                'Product weight': '126,5',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910329',
                ProductName: 'Ovison 1 mg/g crème',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '06-03-2012',
                'N°AMM': '48207',
                'Major Country': 'DK',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290057',
                'Product National Id *': '7350064290057',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '138',
                'Product width': '30',
                'Product heigth': '38',
                'Product weight': '43,3',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910979',
                ProductName: 'Ovison 1 mg/g crème',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '06-03-2012',
                'N°AMM': '48207',
                'Major Country': 'DK',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290057',
                'Product National Id *': '7350064290057',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '138',
                'Product width': '30',
                'Product heigth': '38',
                'Product weight': '43,3',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910337',
                ProductName: 'Ovison 1 mg/g crème',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '06-03-2012',
                'N°AMM': '48207',
                'Major Country': 'DK',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290064',
                'Product National Id *': '7350064290064',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '195',
                'Product width': '38',
                'Product heigth': '44',
                'Product weight': '124,3',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910980',
                ProductName: 'Ovison 1 mg/g crème',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '06-03-2012',
                'N°AMM': '48207',
                'Major Country': 'DK',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290064',
                'Product National Id *': '7350064290064',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '195',
                'Product width': '38',
                'Product heigth': '44',
                'Product weight': '124,3',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910336',
                ProductName: 'Ovixan 0.1 % krem',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '19-01-2012',
                'N°AMM': '10-8121',
                'Major Country': 'NO',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290033',
                'Product National Id *': '7350064290033',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '138',
                'Product width': '30',
                'Product heigth': '38',
                'Product weight': '43,3',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910981',
                ProductName: 'Ovixan 0.1 % krem',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '19-01-2012',
                'N°AMM': '10-8121',
                'Major Country': 'NO',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290033',
                'Product National Id *': '7350064290033',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '138',
                'Product width': '30',
                'Product heigth': '38',
                'Product weight': '43,3',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910338',
                ProductName: 'Ovixan 0.1 % krem',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '19-01-2012',
                'N°AMM': '10-8121',
                'Major Country': 'NO',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290040',
                'Product National Id *': '7350064290040',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '195',
                'Product width': '38',
                'Product heigth': '44',
                'Product weight': '124,3',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910982',
                ProductName: 'Ovixan 0.1 % krem',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '19-01-2012',
                'N°AMM': '10-8121',
                'Major Country': 'NO',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290040',
                'Product National Id *': '7350064290040',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '195',
                'Product width': '38',
                'Product heigth': '44',
                'Product weight': '124,3',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910806',
                ProductName: 'Ovixan 1 mg/g krem',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '07-04-2015',
                'N°AMM': '22371',
                'Major Country': 'PL',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '5909991215095',
                'Product National Id *': '5909991215095',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '138',
                'Product width': '30',
                'Product heigth': '38',
                'Product weight': '43,3',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910988',
                ProductName: 'Ovixan 1 mg/g krem',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '07-04-2015',
                'N°AMM': '22371',
                'Major Country': 'PL',
                'Other Country ': '\n',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '5909991215095',
                'Product National Id *': '5909991215095',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '138',
                'Product width': '30',
                'Product heigth': '38',
                'Product weight': '43,3',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910807',
                ProductName: 'Ovixan 1 mg/g krem',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '07-04-2015',
                'N°AMM': '22371',
                'Major Country': 'PL',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '5909991215101',
                'Product National Id *': '5909991215101',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '195',
                'Product width': '38',
                'Product heigth': '44',
                'Product weight': '124,3',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910989',
                ProductName: 'Ovixan 1 mg/g krem',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '07-04-2015',
                'N°AMM': '22371',
                'Major Country': 'PL',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '5909991215101',
                'Product National Id *': '5909991215101',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '195',
                'Product width': '38',
                'Product heigth': '44',
                'Product weight': '124,3',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910909',
                ProductName: 'Ovixan 1 mg/g krem',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '07-04-2015',
                'N°AMM': '22371',
                'Major Country': 'PL',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '5909991215095',
                'Product National Id *': '5909991215095',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '195',
                'Product width': '38',
                'Product heigth': '44',
                'Product weight': '124,3',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910804',
                ProductName: 'Ovixan 1 mg/g krém',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '11-03-2015',
                'N°AMM': '46/141/15-C',
                'Major Country': 'CZ',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290095',
                'Product National Id *': '7350064290095',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '138',
                'Product width': '30',
                'Product heigth': '38',
                'Product weight': '43,3',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910991',
                ProductName: 'Ovixan 1 mg/g krém',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '11-03-2015',
                'N°AMM': '46/141/15-C',
                'Major Country': 'CZ',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290095',
                'Product National Id *': '7350064290095',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '138',
                'Product width': '30',
                'Product heigth': '38',
                'Product weight': '43,3',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910805',
                ProductName: 'Ovixan 1 mg/g krém',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '11-03-2015',
                'N°AMM': '46/141/15-C',
                'Major Country': 'CZ',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290194',
                'Product National Id *': '7350064290194',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '195',
                'Product width': '38',
                'Product heigth': '44',
                'Product weight': '124,3',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910992',
                ProductName: 'Ovixan 1 mg/g krém',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '11-03-2015',
                'N°AMM': '46/141/15-C',
                'Major Country': 'CZ',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '7350064290194',
                'Product National Id *': '7350064290194',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '195',
                'Product width': '38',
                'Product heigth': '44',
                'Product weight': '124,3',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910770',
                ProductName: 'Ovixan 1 mg/g krema',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '23-11-2015',
                'N°AMM': 'H/15/02081/001',
                'Major Country': 'SI',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '3837000160314',
                'Product National Id *': '3837000160314',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '138',
                'Product width': '30',
                'Product heigth': '38',
                'Product weight': '43,3',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910993',
                ProductName: 'Ovixan 1 mg/g krema',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '23-11-2015',
                'N°AMM': 'H/15/02081/002',
                'Major Country': 'SI',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '3837000160314',
                'Product National Id *': '3837000160314',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '138',
                'Product width': '30',
                'Product heigth': '38',
                'Product weight': '43,3',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910771',
                ProductName: 'Ovixan 1 mg/g krema',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '23-11-2015',
                'N°AMM': 'H/15/02081/001',
                'Major Country': 'SI',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '3837000160437',
                'Product National Id *': '3837000160437',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '195',
                'Product width': '38',
                'Product heigth': '44',
                'Product weight': '124,3',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            },
            {
                ProductId: '910994',
                ProductName: 'Ovixan 1 mg/g krema',
                'Generic Name': 'Mometasone furoate',
                Family: 'Mometasone furoate',
                Description: 'Mometasone furoate',
                Strength: '1',
                'Unit ': 'mg/g',
                'Refunded ': '',
                'With a prescription': 'YES',
                'Risk of falsification': 'YES',
                Lifetime: '',
                LifetimeType: '',
                AMM: 'YES',
                'AMM Date': '23-11-2015',
                'N°AMM': 'H/15/02081/002',
                'Major Country': 'SI',
                'Other Country ': '',
                'Packaging type': '',
                'Product form': 'Cream',
                'Code article 57': '',
                'GTIN*': '3837000160437',
                'Product National Id *': '3837000160437',
                'Pack Type* ': '',
                'Quantity *': '',
                'Product length': '195',
                'Product width': '38',
                'Product heigth': '44',
                'Product weight': '124,3',
                'Tamper evident Y/N': 'Y',
                'Serialization configuration': '',
                'Box / case GTIN*': '',
                'Box National Id *': '',
                'Box length': '',
                'Box width': '',
                'Box heigth': '',
                'Box weight': '',
                'Box Product variants (AI20)': '',
                'Partner ': 'Galenica',
                'Production site ': 'Bioglan, Malmoe'
            }
        ]
        const keysDepth = ['Generic Name', 'ProductName', 'Product form', 'Strength', 'Major Country']
        const jsonTree = generateTree(data, keysDepth)
        console.log(JSON.stringify(jsonTree, null, 2))
        const expectedResult = {
            "Mometasone furoate": {
                "Ovixan 1 mg/g\nkräm/krem/emulsiovoide": {
                    "Cream": {
                        "1": {
                            "SE": {
                                "ProductId": "910975",
                                "ProductName": "Ovixan 1 mg/g\nkräm/krem/emulsiovoide",
                                "Generic Name": "Mometasone furoate",
                                "Family": "Mometasone furoate",
                                "Description": "Mometasone furoate",
                                "Strength": "1",
                                "Unit ": "mg/g",
                                "Refunded ": "",
                                "With a prescription": "YES",
                                "Risk of falsification": "YES",
                                "Lifetime": "",
                                "LifetimeType": "",
                                "AMM": "YES",
                                "AMM Date": "29-03-2012",
                                "N°AMM": "45580",
                                "Major Country": "SE",
                                "Other Country ": "",
                                "Packaging type": "",
                                "Product form": "Cream",
                                "Code article 57": "",
                                "GTIN*": "7350064290019",
                                "Product National Id *": "7350064290019",
                                "Pack Type* ": "",
                                "Quantity *": "",
                                "Product length": "138",
                                "Product width": "30",
                                "Product heigth": "38",
                                "Product weight": "45,5",
                                "Tamper evident Y/N": "Y",
                                "Serialization configuration": "",
                                "Box / case GTIN*": "",
                                "Box National Id *": "",
                                "Box length": "",
                                "Box width": "",
                                "Box heigth": "",
                                "Box weight": "",
                                "Box Product variants (AI20)": "",
                                "Partner ": "Galenica",
                                "Production site ": "Bioglan, Malmoe"
                            },
                            "IS": {
                                "ProductId": "910975",
                                "ProductName": "Ovixan 1 mg/g\nkräm/krem/emulsiovoide",
                                "Generic Name": "Mometasone furoate",
                                "Family": "Mometasone furoate",
                                "Description": "Mometasone furoate",
                                "Strength": "1",
                                "Unit ": "mg/g",
                                "Refunded ": "",
                                "With a prescription": "YES",
                                "Risk of falsification": "YES",
                                "Lifetime": "",
                                "LifetimeType": "",
                                "AMM": "YES",
                                "AMM Date": "29-12-2011",
                                "N°AMM": "IS/1/11/136/01",
                                "Major Country": "IS",
                                "Other Country ": "",
                                "Packaging type": "",
                                "Product form": "Cream",
                                "Code article 57": "",
                                "GTIN*": "7350064290019",
                                "Product National Id *": "7350064290019",
                                "Pack Type* ": "",
                                "Quantity *": "",
                                "Product length": "138",
                                "Product width": "30",
                                "Product heigth": "38",
                                "Product weight": "45,5",
                                "Tamper evident Y/N": "Y",
                                "Serialization configuration": "",
                                "Box / case GTIN*": "",
                                "Box National Id *": "",
                                "Box length": "",
                                "Box width": "",
                                "Box heigth": "",
                                "Box weight": "",
                                "Box Product variants (AI20)": "",
                                "Partner ": "Galenica",
                                "Production site ": "Bioglan, Malmoe"
                            }
                        }
                    }
                },
                "Ovixan 1 mg/g kräm/krem/emulsiovoide": {
                    "Cream": {
                        "1": {
                            "SE": {
                                "ProductId": "910976",
                                "ProductName": "Ovixan 1 mg/g kräm/krem/emulsiovoide",
                                "Generic Name": "Mometasone furoate",
                                "Family": "Mometasone furoate",
                                "Description": "Mometasone furoate",
                                "Strength": "1",
                                "Unit ": "mg/g",
                                "Refunded ": "",
                                "With a prescription": "YES",
                                "Risk of falsification": "YES",
                                "Lifetime": "",
                                "LifetimeType": "",
                                "AMM": "YES",
                                "AMM Date": "29-03-2012",
                                "N°AMM": "45580",
                                "Major Country": "SE",
                                "Other Country ": "",
                                "Packaging type": "",
                                "Product form": "Cream",
                                "Code article 57": "",
                                "GTIN*": "7350064290026",
                                "Product National Id *": "7350064290026",
                                "Pack Type* ": "",
                                "Quantity *": "",
                                "Product length": "195",
                                "Product width": "38",
                                "Product heigth": "44",
                                "Product weight": "126,5",
                                "Tamper evident Y/N": "Y",
                                "Serialization configuration": "",
                                "Box / case GTIN*": "",
                                "Box National Id *": "",
                                "Box length": "",
                                "Box width": "",
                                "Box heigth": "",
                                "Box weight": "",
                                "Box Product variants (AI20)": "",
                                "Partner ": "Galenica",
                                "Production site ": "Bioglan, Malmoe"
                            }
                        }
                    }
                },
                "Ovison 1 mg/g crème": {
                    "Cream": {
                        "1": {
                            "DK": {
                                "ProductId": "910980",
                                "ProductName": "Ovison 1 mg/g crème",
                                "Generic Name": "Mometasone furoate",
                                "Family": "Mometasone furoate",
                                "Description": "Mometasone furoate",
                                "Strength": "1",
                                "Unit ": "mg/g",
                                "Refunded ": "",
                                "With a prescription": "YES",
                                "Risk of falsification": "YES",
                                "Lifetime": "",
                                "LifetimeType": "",
                                "AMM": "YES",
                                "AMM Date": "06-03-2012",
                                "N°AMM": "48207",
                                "Major Country": "DK",
                                "Other Country ": "",
                                "Packaging type": "",
                                "Product form": "Cream",
                                "Code article 57": "",
                                "GTIN*": "7350064290064",
                                "Product National Id *": "7350064290064",
                                "Pack Type* ": "",
                                "Quantity *": "",
                                "Product length": "195",
                                "Product width": "38",
                                "Product heigth": "44",
                                "Product weight": "124,3",
                                "Tamper evident Y/N": "Y",
                                "Serialization configuration": "",
                                "Box / case GTIN*": "",
                                "Box National Id *": "",
                                "Box length": "",
                                "Box width": "",
                                "Box heigth": "",
                                "Box weight": "",
                                "Box Product variants (AI20)": "",
                                "Partner ": "Galenica",
                                "Production site ": "Bioglan, Malmoe"
                            }
                        }
                    }
                },
                "Ovixan 0.1 % krem": {
                    "Cream": {
                        "1": {
                            "NO": {
                                "ProductId": "910982",
                                "ProductName": "Ovixan 0.1 % krem",
                                "Generic Name": "Mometasone furoate",
                                "Family": "Mometasone furoate",
                                "Description": "Mometasone furoate",
                                "Strength": "1",
                                "Unit ": "mg/g",
                                "Refunded ": "",
                                "With a prescription": "YES",
                                "Risk of falsification": "YES",
                                "Lifetime": "",
                                "LifetimeType": "",
                                "AMM": "YES",
                                "AMM Date": "19-01-2012",
                                "N°AMM": "10-8121",
                                "Major Country": "NO",
                                "Other Country ": "",
                                "Packaging type": "",
                                "Product form": "Cream",
                                "Code article 57": "",
                                "GTIN*": "7350064290040",
                                "Product National Id *": "7350064290040",
                                "Pack Type* ": "",
                                "Quantity *": "",
                                "Product length": "195",
                                "Product width": "38",
                                "Product heigth": "44",
                                "Product weight": "124,3",
                                "Tamper evident Y/N": "Y",
                                "Serialization configuration": "",
                                "Box / case GTIN*": "",
                                "Box National Id *": "",
                                "Box length": "",
                                "Box width": "",
                                "Box heigth": "",
                                "Box weight": "",
                                "Box Product variants (AI20)": "",
                                "Partner ": "Galenica",
                                "Production site ": "Bioglan, Malmoe"
                            }
                        }
                    }
                },
                "Ovixan 1 mg/g krem": {
                    "Cream": {
                        "1": {
                            "PL": {
                                "ProductId": "910909",
                                "ProductName": "Ovixan 1 mg/g krem",
                                "Generic Name": "Mometasone furoate",
                                "Family": "Mometasone furoate",
                                "Description": "Mometasone furoate",
                                "Strength": "1",
                                "Unit ": "mg/g",
                                "Refunded ": "",
                                "With a prescription": "YES",
                                "Risk of falsification": "YES",
                                "Lifetime": "",
                                "LifetimeType": "",
                                "AMM": "YES",
                                "AMM Date": "07-04-2015",
                                "N°AMM": "22371",
                                "Major Country": "PL",
                                "Other Country ": "",
                                "Packaging type": "",
                                "Product form": "Cream",
                                "Code article 57": "",
                                "GTIN*": "5909991215095",
                                "Product National Id *": "5909991215095",
                                "Pack Type* ": "",
                                "Quantity *": "",
                                "Product length": "195",
                                "Product width": "38",
                                "Product heigth": "44",
                                "Product weight": "124,3",
                                "Tamper evident Y/N": "Y",
                                "Serialization configuration": "",
                                "Box / case GTIN*": "",
                                "Box National Id *": "",
                                "Box length": "",
                                "Box width": "",
                                "Box heigth": "",
                                "Box weight": "",
                                "Box Product variants (AI20)": "",
                                "Partner ": "Galenica",
                                "Production site ": "Bioglan, Malmoe"
                            }
                        }
                    }
                },
                "Ovixan 1 mg/g krém": {
                    "Cream": {
                        "1": {
                            "CZ": {
                                "ProductId": "910992",
                                "ProductName": "Ovixan 1 mg/g krém",
                                "Generic Name": "Mometasone furoate",
                                "Family": "Mometasone furoate",
                                "Description": "Mometasone furoate",
                                "Strength": "1",
                                "Unit ": "mg/g",
                                "Refunded ": "",
                                "With a prescription": "YES",
                                "Risk of falsification": "YES",
                                "Lifetime": "",
                                "LifetimeType": "",
                                "AMM": "YES",
                                "AMM Date": "11-03-2015",
                                "N°AMM": "46/141/15-C",
                                "Major Country": "CZ",
                                "Other Country ": "",
                                "Packaging type": "",
                                "Product form": "Cream",
                                "Code article 57": "",
                                "GTIN*": "7350064290194",
                                "Product National Id *": "7350064290194",
                                "Pack Type* ": "",
                                "Quantity *": "",
                                "Product length": "195",
                                "Product width": "38",
                                "Product heigth": "44",
                                "Product weight": "124,3",
                                "Tamper evident Y/N": "Y",
                                "Serialization configuration": "",
                                "Box / case GTIN*": "",
                                "Box National Id *": "",
                                "Box length": "",
                                "Box width": "",
                                "Box heigth": "",
                                "Box weight": "",
                                "Box Product variants (AI20)": "",
                                "Partner ": "Galenica",
                                "Production site ": "Bioglan, Malmoe"
                            }
                        }
                    }
                },
                "Ovixan 1 mg/g krema": {
                    "Cream": {
                        "1": {
                            "SI": {
                                "ProductId": "910994",
                                "ProductName": "Ovixan 1 mg/g krema",
                                "Generic Name": "Mometasone furoate",
                                "Family": "Mometasone furoate",
                                "Description": "Mometasone furoate",
                                "Strength": "1",
                                "Unit ": "mg/g",
                                "Refunded ": "",
                                "With a prescription": "YES",
                                "Risk of falsification": "YES",
                                "Lifetime": "",
                                "LifetimeType": "",
                                "AMM": "YES",
                                "AMM Date": "23-11-2015",
                                "N°AMM": "H/15/02081/002",
                                "Major Country": "SI",
                                "Other Country ": "",
                                "Packaging type": "",
                                "Product form": "Cream",
                                "Code article 57": "",
                                "GTIN*": "3837000160437",
                                "Product National Id *": "3837000160437",
                                "Pack Type* ": "",
                                "Quantity *": "",
                                "Product length": "195",
                                "Product width": "38",
                                "Product heigth": "44",
                                "Product weight": "124,3",
                                "Tamper evident Y/N": "Y",
                                "Serialization configuration": "",
                                "Box / case GTIN*": "",
                                "Box National Id *": "",
                                "Box length": "",
                                "Box width": "",
                                "Box heigth": "",
                                "Box weight": "",
                                "Box Product variants (AI20)": "",
                                "Partner ": "Galenica",
                                "Production site ": "Bioglan, Malmoe"
                            }
                        }
                    }
                }
            },
            "Mometasone furoate1": {
                "Ovixan 1 mg/g kräm/krem/emulsiovoide1": {
                    "Cream": {
                        "1": {
                            "IS": {
                                "ProductId": "910256",
                                "ProductName": "Ovixan 1 mg/g kräm/krem/emulsiovoide1",
                                "Generic Name": "Mometasone furoate1",
                                "Family": "Mometasone furoate",
                                "Description": "Mometasone furoate",
                                "Strength": "1",
                                "Unit ": "mg/g",
                                "Refunded ": "",
                                "With a prescription": "YES",
                                "Risk of falsification": "YES",
                                "Lifetime": "",
                                "LifetimeType": "",
                                "AMM": "YES",
                                "AMM Date": "29-12-2011",
                                "N°AMM": "IS/1/11/136/01",
                                "Major Country": "IS",
                                "Other Country ": "",
                                "Packaging type": "",
                                "Product form": "Cream",
                                "Code article 57": "",
                                "GTIN*": "7350064290026",
                                "Product National Id *": "7350064290026",
                                "Pack Type* ": "",
                                "Quantity *": "",
                                "Product length": "195",
                                "Product width": "38",
                                "Product heigth": "44",
                                "Product weight": "126,5",
                                "Tamper evident Y/N": "Y",
                                "Serialization configuration": "",
                                "Box / case GTIN*": "",
                                "Box National Id *": "",
                                "Box length": "",
                                "Box width": "",
                                "Box heigth": "",
                                "Box weight": "",
                                "Box Product variants (AI20)": "",
                                "Partner ": "Galenica",
                                "Production site ": "Bioglan, Malmoe"
                            }
                        }
                    },
                    "Cream1": {
                        "1": {
                            "IS": {
                                "ProductId": "910976",
                                "ProductName": "Ovixan 1 mg/g kräm/krem/emulsiovoide1",
                                "Generic Name": "Mometasone furoate1",
                                "Family": "Mometasone furoate",
                                "Description": "Mometasone furoate",
                                "Strength": "1",
                                "Unit ": "mg/g",
                                "Refunded ": "",
                                "With a prescription": "YES",
                                "Risk of falsification": "YES",
                                "Lifetime": "",
                                "LifetimeType": "",
                                "AMM": "YES",
                                "AMM Date": "29-12-2011",
                                "N°AMM": "IS/1/11/136/01",
                                "Major Country": "IS",
                                "Other Country ": "",
                                "Packaging type": "",
                                "Product form": "Cream1",
                                "Code article 57": "",
                                "GTIN*": "7350064290026",
                                "Product National Id *": "7350064290026",
                                "Pack Type* ": "",
                                "Quantity *": "",
                                "Product length": "195",
                                "Product width": "38",
                                "Product heigth": "44",
                                "Product weight": "126,5",
                                "Tamper evident Y/N": "Y",
                                "Serialization configuration": "",
                                "Box / case GTIN*": "",
                                "Box National Id *": "",
                                "Box length": "",
                                "Box width": "",
                                "Box heigth": "",
                                "Box weight": "",
                                "Box Product variants (AI20)": "",
                                "Partner ": "Galenica",
                                "Production site ": "Bioglan, Malmoe"
                            }
                        }
                    },
                    "Cream2": {
                        "1": {
                            "FI": {
                                "ProductId": "910255",
                                "ProductName": "Ovixan 1 mg/g kräm/krem/emulsiovoide1",
                                "Generic Name": "Mometasone furoate1",
                                "Family": "Mometasone furoate",
                                "Description": "Mometasone furoate",
                                "Strength": "1",
                                "Unit ": "mg/g",
                                "Refunded ": "",
                                "With a prescription": "YES",
                                "Risk of falsification": "YES",
                                "Lifetime": "",
                                "LifetimeType": "",
                                "AMM": "YES",
                                "AMM Date": "11-01-2012",
                                "N°AMM": "29453",
                                "Major Country": "FI",
                                "Other Country ": "",
                                "Packaging type": "",
                                "Product form": "Cream2",
                                "Code article 57": "",
                                "GTIN*": "7350064290224",
                                "Product National Id *": "7350064290224",
                                "Pack Type* ": "",
                                "Quantity *": "",
                                "Product length": "138",
                                "Product width": "30",
                                "Product heigth": "38",
                                "Product weight": "45,5",
                                "Tamper evident Y/N": "Y",
                                "Serialization configuration": "",
                                "Box / case GTIN*": "",
                                "Box National Id *": "",
                                "Box length": "",
                                "Box width": "",
                                "Box heigth": "",
                                "Box weight": "",
                                "Box Product variants (AI20)": "",
                                "Partner ": "Galenica",
                                "Production site ": "Bioglan, Malmoe"
                            }
                        }
                    }
                },
                "Ovixan 1 mg/g kräm/krem/emulsiovoide": {
                    "Cream": {
                        "1": {
                            "FI": {
                                "ProductId": "910978",
                                "ProductName": "Ovixan 1 mg/g kräm/krem/emulsiovoide",
                                "Generic Name": "Mometasone furoate1",
                                "Family": "Mometasone furoate",
                                "Description": "Mometasone furoate",
                                "Strength": "1",
                                "Unit ": "mg/g",
                                "Refunded ": "",
                                "With a prescription": "YES",
                                "Risk of falsification": "YES",
                                "Lifetime": "",
                                "LifetimeType": "",
                                "AMM": "YES",
                                "AMM Date": "11-01-2012",
                                "N°AMM": "29453",
                                "Major Country": "FI",
                                "Other Country ": "",
                                "Packaging type": "",
                                "Product form": "Cream",
                                "Code article 57": "",
                                "GTIN*": "7350064290231",
                                "Product National Id *": "7350064290231",
                                "Pack Type* ": "",
                                "Quantity *": "",
                                "Product length": "195",
                                "Product width": "38",
                                "Product heigth": "44",
                                "Product weight": "126,5",
                                "Tamper evident Y/N": "Y",
                                "Serialization configuration": "",
                                "Box / case GTIN*": "",
                                "Box National Id *": "",
                                "Box length": "",
                                "Box width": "",
                                "Box heigth": "",
                                "Box weight": "",
                                "Box Product variants (AI20)": "",
                                "Partner ": "Galenica",
                                "Production site ": "Bioglan, Malmoe"
                            }
                        }
                    }
                }
            }
        }
        assert.deepStrictEqual(jsonTree, expectedResult)
    })
})